/**
 * Fecha
 * original: Date
 */
module.exports = {
  // metodos
  aFechaEnTexto: 'toDateString',
  aFechaEnTextoLocalizada: 'toLocaleDateString',
  aFormatoLocalizado: 'toLocaleFormat',
  ahora: 'now',
  aJSON: 'toJSON',
  aTextoISO: 'toISOString',
  aTextoUTC: 'toUTCString',
  aTiempoEnTexto: 'toTimeString',
  aTiempoEnTextoLocalizado: 'toLocaleTimeString',
  convertir: 'parse',
  definirAnioCompleto: 'setFullYear',
  definirAnioCompletoUTC: 'setUTCFullYear',
  definirFecha: 'setDate',
  definirFechaUTC: 'setUTCDate',
  definirHoras: 'setHours',
  definirHorasUTC: 'setUTCHours',
  definirMes: 'setMonth',
  definirMesUTC: 'setUTCMonth',
  definirMilisegundos: 'setMilliseconds',
  definirMilisegundosUTC: 'setUTCMilliseconds',
  definirMinutos: 'setMinutes',
  definirMinutosUTC: 'setUTCMinutes',
  definirSegundos: 'setSeconds',
  definirSegundosUTC: 'setUTCSeconds',
  definirTiempo: 'setTime',
  obtenerAnioCompleto: 'getFullYear',
  obtenerAnioCompletoUTC: 'getUTCFullYear',
  obtenerDesfaceUsoHorario: 'getTimezoneOffset',
  obtenerDia: 'getDay',
  obtenerDiaUTC: 'getUTCDay',
  obtenerFecha: 'getDate',
  obtenerFechaUTC: 'getUTCDate',
  obtenerHoras: 'getHours',
  obtenerHorasUTC: 'getUTCHours',
  obtenerMes: 'getMonth',
  obtenerMesUTC: 'getUTCMonth',
  obtenerMilisegundos: 'getMilliseconds',
  obtenerMilisegundosUTC: 'getUTCMilliseconds',
  obtenerMinutos: 'getMinutes',
  obtenerMinutosUTC: 'getUTCMinutes',
  obtenerSegundos: 'getSeconds',
  obtenerSegundosUTC: 'getUTCSeconds',
  obtenerTiempo: 'getTime',
  UTC: 'UTC',
};
